### ISSUE TITLE
to curl or not to curl

### ISSUE THREAD

**Issue by binamov** [chef-training/chef-essentials-windows#18]
Section 3, slide 39, Invites the participants to test their awesome new website by running `curl localhost`. This course was developed on Windows images where `curl` was linked to the `Invoke-WebRequest` PowerShell cmdlet and the command worked.

I recently delivered this course on workstation AMI `ami-52a0a638` and students reported that `curl` wasn't linked on instances.

A kind person pointed out that the Windows-y way to `curl` is to `Invoke-WebRequest`. Usage is similar to curl, so, slide 3-39 could be adjusted to say `Invoke-WebRequest localhost`.

**Comment by burtlo** [comment]
That change will be made.
