### ISSUE TITLE
Slide 11-8 : Incorrect Command

### ISSUE THREAD

**Issue by larryebaum** [chef-training/chef-essentials-windows#25]
The indicated command is incorrect: knife winrm *:* -x USERNAME -P PASSWORD –a ipaddress "chef-client". The -a value SHOULD BE cloud.public_ipv4, thus the full command:
> knife winrm *:* -x USERNAME -P PASSWORD –a cloud.public_ipv4 "chef-client"

**Comment by SteveDelFante** [comment]
Fixed. Will close later.
