### ISSUE TITLE
Module 5 - Test Kitchen - Wrong InSpec expectations does not yield the correct results

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-essentials-windows#30]
> I ran through the new windows training last week and noticed the inspec test for the website file is wrong. `Invoke-WebRequest` returns an object in powershell, so if you want to check what the content is you need `(Invoke-WebRequest).Content`

**Comment by SteveDelFante** [comment]
@frank Are you saying I should replace all instances of `Invoke-WebRequest` in Module 5 with `(Invoke-WebRequest).Content` ?

**Comment by burtlo** [comment]
I would test it. I haven't had a chance to do that. This was feedback from someone that taught the course and I didn't get a screenshot or error output and the corrected output.

**Comment by SteveDelFante** [comment]
The original `Invoke-WebRequest` string was correct.
